library(readxl)
library(forecast)
library(leaps)
library(MASS)
library(tidyverse)
library(forcats)
setwd("C:/Users/n077511/Box Sync/WEMBA DOCS/Courses/Forecasting and Predictive Analytics/Project")
iowatrain = read.csv("train.csv")
iowatest = read.csv("test.csv")
## making sure these columns are numeric and not factors
iowatrain$LotFrontage = as.numeric(as.character(iowatrain$LotFrontage))
iowatrain$MasVnrArea = as.numeric(as.character(iowatrain$MasVnrArea))
iowatrain$GarageYrBlt = as.numeric(as.character(iowatrain$GarageYrBlt))
##Identifying which factor columns have NAs to be recoded
sapply(iowatrain, function(x) sum(is.na(x)))
## levels in Factor columns
iowatrain$Alley = forcats::fct_explicit_na(iowatrain$Alley, "No Access")
iowatrain$MasVnrType = forcats::fct_explicit_na(iowatrain$MasVnrType,"")
iowatrain$BsmtQual = forcats::fct_explicit_na(iowatrain$BsmtQual,"No Basement")
iowatrain$Bsmtcondl = forcats::fct_explicit_na(iowatrain$BsmtCond,"No Basement")
iowatrain$BsmtExposure = forcats::fct_explicit_na(iowatrain$BsmtExposure,"No Basement")
iowatrain$BsmtFinType1 = forcats::fct_explicit_na(iowatrain$BsmtFinType1,"No Basement")
iowatrain$BsmtFinType2 = forcats::fct_explicit_na(iowatrain$BsmtFinType2,"No Basement")
iowatrain$Electrical = forcats::fct_explicit_na(iowatrain$Electrical,"")
iowatrain$FireplaceQu = forcats::fct_explicit_na(iowatrain$FireplaceQu,"No Fireplace")
iowatrain$GarageType = forcats::fct_explicit_na(iowatrain$GarageType,"No Garage")
iowatrain$GarageFinish = forcats::fct_explicit_na(iowatrain$GarageFinish,"No Garage")
iowatrain$GarageQual = forcats::fct_explicit_na(iowatrain$GarageQual,"No Garage")
iowatrain$GarageCond = forcats::fct_explicit_na(iowatrain$GarageCond,"No Garage")
iowatrain$PoolQC = forcats::fct_explicit_na(iowatrain$PoolQC,"No Pool")
iowatrain$Fence = forcats::fct_explicit_na(iowatrain$Fence,"No Fence")
iowatrain$MiscFeature = forcats::fct_explicit_na(iowatrain$MiscFeature,"None")
## Removing NA in the numeric columns
iowatrain = tidyr::replace_na(iowatrain, list(LotFrontage = "", MasVnrArea = "", GarageYrBlt = ""))
## Linear Regression Model. 
reg = lm(SalePrice ~. -Id -Utilities -Condition2, data = iowatrain)
summary(reg)